version : "3.8"

services:
  frontendimg :
    build : /root/Doc_Three_Tier/frontend
    container_name: frontend
    ports:
    - "80:80"
    network_mode: bridge

  backendimg :
   build : /root/Doc_Three_Tier/backend
   container_name: backend
   ports:
   - "8080:8080"
   network_mode: bridge
   depends_on: 
   - "frontendimg"
